# -- encoding: utf-8 --
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from apps.authentication.models import Rol
from core.settings import AUTH_USER_MODEL

class Empleado(models.Model):
    usuario_registro = models.ForeignKey(AUTH_USER_MODEL, related_name='empleados_registro', on_delete=models.PROTECT)
    usuario_modificacion = models.ForeignKey(AUTH_USER_MODEL, related_name='empleados_modificacion', on_delete=models.PROTECT, blank=True, null=True)
    rol = models.ForeignKey(Rol, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    id_admin = models.IntegerField()
    nombre = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50, blank=True, null=True)
    sexo = models.CharField(max_length=10)
    rfc = models.CharField(max_length=13, blank=True, null=True)
    curp = models.CharField(max_length=50, blank=True, null=True)
    clave_empleado = models.CharField(max_length=50, blank=True, null=True)
    activo = models.BooleanField(default=True)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    celular = models.CharField(max_length=13, blank=True, null=True)
    codigo_rol = models.CharField(max_length=10, blank=True, null=True)
    empleado_imagen = models.TextField(blank=True, null=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)

class Movimiento(models.Model):
    empleado = models.ForeignKey(Empleado, related_name='movimientos', on_delete=models.PROTECT, blank=True, null=True)
    surtidor_inicio = models.ForeignKey(Empleado, related_name='surtidor_inicio', on_delete=models.PROTECT, blank=True, null=True)
    panel = models.ForeignKey(Empleado, related_name='panel', on_delete=models.PROTECT, blank=True, null=True)
    repartidor = models.ForeignKey(Empleado, related_name='reparador', on_delete=models.PROTECT, blank=True, null=True)
    id_admin = models.IntegerField()
    fecha_movimiento = models.DateTimeField()
    condicion = models.CharField(max_length=250, blank=True, null=True)
    almacen = models.CharField(max_length=250)
    folio = models.IntegerField()
    serie = models.CharField(max_length=250, blank=True, null=True)
    folio_adicional = models.CharField(max_length=250, blank=True, null=True)
    cliente = models.CharField(max_length=250)
    sucursal = models.CharField(max_length=250, blank=True, null=True)
    pagado = models.BooleanField(default=False)
    metodo_pago = models.CharField(max_length=250)
    cantidad_pedida = models.FloatField()
    importe_pedido = models.FloatField()
    iva_pedido = models.FloatField()
    descuento_pedido = models.FloatField()
    total_pedido = models.FloatField()
    costo_venta = models.FloatField()
    utilidad = models.FloatField()
    moneda = models.CharField(max_length=250)
    orden_id_admin = models.IntegerField(blank=True, null=True)
    tipo_movimiento = models.CharField(max_length=250)
    cancelado = models.BooleanField(default=False)
    facturado = models.BooleanField(default=False)
    devolucion = models.BooleanField(default=False)
    solo_domicilio = models.BooleanField(default=False)
    cod = models.BooleanField(default=False)
    codigo_surtidor = models.CharField(max_length=10, blank=True, null=True)
    codigo_panel = models.CharField(max_length=10, blank=True, null=True)
    codigo_repartidor = models.CharField(max_length=10, blank=True, null=True)
    fecha_surtiendo = models.DateTimeField(blank=True, null=True)
    fecha_entrega = models.DateTimeField(blank=True, null=True)
    fecha_inicio_repartidor = models.DateTimeField(blank=True, null=True)
    fecha_final_repartidor = models.DateTimeField(blank=True, null=True)
    cantidad_entregada = models.FloatField(blank=True, null=True)
    importe_entregado = models.FloatField(blank=True, null=True)
    iva_entregado = models.FloatField(blank=True, null=True)
    descuento_entregado = models.FloatField(blank=True, null=True)
    total_entregado = models.FloatField(blank=True, null=True)
    status = models.CharField(max_length=32)

class MovimientoDetalle(models.Model):
    movimiento = models.ForeignKey(Movimiento, related_name='movimiento_detalle', on_delete=models.PROTECT)
    usuario_registro = models.ForeignKey(AUTH_USER_MODEL, related_name='movimiento_detalle_registro', on_delete=models.PROTECT)
    usuario_modificacion = models.ForeignKey(AUTH_USER_MODEL, related_name='movimiento_detalle_modificacion', on_delete=models.PROTECT, blank=True, null=True)
    id_admin = models.IntegerField()
    codigo_producto = models.CharField(max_length=250)
    producto = models.CharField(max_length=250)
    unidad_medida = models.CharField(max_length=250)
    cantidad_pedida = models.FloatField()
    factor_um = models.FloatField()
    precio_unitario = models.FloatField()
    importe_pedido = models.FloatField()
    iva_pedido = models.FloatField()
    descuento_pedido = models.FloatField()
    total_pedido = models.FloatField()
    cantidad_entregada = models.FloatField(blank=True, null=True)
    importe_entregado = models.FloatField(blank=True, null=True)
    iva_entregado = models.FloatField(blank=True, null=True)
    descuento_entregado = models.FloatField(blank=True, null=True)
    total_entregado = models.FloatField(blank=True, null=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, blank=True, null=True)
    observacion = models.TextField(blank=True, null=True)

# Create your models here.