# Generated by Django 3.2.6 on 2024-12-14 03:41

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Rol = apps.get_model('authentication', 'Rol')
    roles = ['Administrador', 'Surtidor', 'Panel', 'Repartidor']
    for role in roles:
        if not Rol.objects.filter(nombre=role).exists():
            Rol.objects.create(nombre=role)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)        
    ]